#!/usr/bin/env bash
########################################################################
# Builds the libfossil.c/h amalgamation and related files. Intended to
# be run from the top of the build tree.
#
# Usage: $0 [flags - described below]
#
# Output is several files named libfossil*.*.
#
########################################################################

set -uo pipefail
IFS=$'\n\t'

echo "WARNING: this script Will Cause Grief when run multiple times in parallel (e.g. via make -j4)."

function die(){
    local rc=$1
    shift
    echo "$0: fatal: $@" 1>&2
    exit $rc
}

function requireBin(){
  for i in "$@"; do
    which $i &>/dev/null || die $? "Missing required binary: $i"
  done
}

if uname -a | grep Haiku >/dev/null; then
  if [ ! -f jimsh0 ]; then
    echo "Note: building jimsh0 because Haiku R5's tclsh inexplicably chokes on the next steps."
    cc -o jimsh0 autosetup/jimsh0.c -DHAVE_REALPATH || die $? "Compilation of jimsh0 failed!"
  fi
fi

doZip=0
doUv=0
compileC=1
compileCpp=0
beQuiet=0
TOPDIR=${TOPDIR-$PWD}; # top dir of source tree. Needs to be set
                       # explicitly for out-of-tree builds.
for i in "$@"; do
  case $i in
    -uv) requireBin fossil; doUv=1; doZip=1;;
    -zip) requireBin zip; doZip=1 ;;
    -nc|--no-compile) compileC=0 ;;
    -c++|--compile-c++) compileCpp=1 ;;
    -q|--quiet) beQuiet=1 ;;
    -?|--help|-help)
      cat <<EOF
Usage: $0 [flags]

Creates the libfossil amalgamations, emiting several files named
libfossil*.*. Expects to be run from the top-most source directory of
a libfossil checkout.

Flags:

  -zip = build zip file

  -uv  = add amalgamation to fossil unversioned content IF in a checkout

  -nc|--no-compile = skip the C compilation sanity check

  -c++|--compile-c++ = sanity-check compile the C++ bits (normally skipped)

  -q|--quiet = be less verbose (but not silent)

  -?|--help|-help = show this message and exit

Note that the C++ bits are not part of the standard amalgamation
distribution, so are not included in the resulting ZIP and
"unversioned files" content.

EOF
      exit 0
      ;;
    *) die 1 "Unhandled argument: $i" ;;
  esac
done

amalC=libfossil.c
amalH=libfossil.h
amalConf=libfossil-config.h
amalHtml=amalgamation.html
amalZip=libfossil-amalgamation.zip

dInc=include
dIncF=${dInc}/fossil-scm
dSrcF=src
ahIn=(
  ${dIncF}/config.h
  ${dIncF}/util.h
  ${dIncF}/core.h
  ${dIncF}/db.h
  ${dIncF}/hash.h
  ${dIncF}/repo.h
  ${dIncF}/checkout.h
  ${dIncF}/confdb.h
  ${dIncF}/vpath.h
  ${dIncF}/auth.h
  ${dIncF}/forum.h
  ${dIncF}/sync.h
  ${dIncF}/pages.h
  ${dIncF}/cli.h
  ${dIncF}/deprecated.h
)

acIn=(
  # This list (mostly) corresponds to $(libf.SRC) in the makefile
  ${dSrcF}/xdirent.h
  ${dIncF}/internal.h
  ${dSrcF}/fsl.c
  ${dSrcF}/annotate.c
  ${dSrcF}/appendf.c
  ${dSrcF}/auth.c
  ${dSrcF}/bag.c
  ${dSrcF}/buffer.c
  ${dSrcF}/cache.c
  ${dSrcF}/checkin.c
  ${dSrcF}/checkout.c
  ${dSrcF}/cli.c
  ${dSrcF}/content.c
  ${dSrcF}/config.c
  ${dSrcF}/ext_regexp.h
  ${dSrcF}/ext_regexp.c
  ${dSrcF}/cx.c
  ${dSrcF}/db.c
  ${dSrcF}/deck.c
  ${dSrcF}/delta.c
  ${dSrcF}/dibu.c
  ${dSrcF}/diff.c
  ${dSrcF}/encode.c
  ${dSrcF}/event.c
  ${dSrcF}/foci.c
  ${dSrcF}/fs.c
  ${dSrcF}/forum.c
  ${dSrcF}/glob.c
  ${dSrcF}/io.c
  ${dSrcF}/leaf.c
  ${dSrcF}/list.c
  ${dSrcF}/lookslike.c
  ${dSrcF}/md5.c
  ${dSrcF}/merge.c
  ${dSrcF}/merge3.c
  ${dSrcF}/msg.c
  ${dSrcF}/popen.c
  ${dSrcF}/pq.c
  ${dSrcF}/repo.c
  ${dSrcF}/sc.c
  ${dSrcF}/schema.c
  ${dSrcF}/search.c
  ${dSrcF}/sha1.c
  ${dSrcF}/sha3.c
  ${dSrcF}/strftime.c
  ${dSrcF}/tag.c
  ${dSrcF}/ticket.c
  ${dSrcF}/udf.c
  ${dSrcF}/url.c
  ${dSrcF}/utf8.c
  ${dSrcF}/vfile.c
  ${dSrcF}/vpath.c
  ${dSrcF}/wiki.c
  ${dSrcF}/xfer.c
  ${dSrcF}/zip.c
  ${dSrcF}/difftk_cstr.c
  ${dSrcF}/schema_config_cstr.c
  ${dSrcF}/schema_repo1_cstr.c
  ${dSrcF}/schema_repo2_cstr.c
  ${dSrcF}/schema_ckout_cstr.c
  ${dSrcF}/schema_ticket_cstr.c
  ${dSrcF}/schema_ticket_reports_cstr.c
  ${dSrcF}/schema_forum_cstr.c
)

########################################################################
echo "Generating ${amalConf}..."
/bin/sh $TOPDIR/configure --amal >/dev/null || die $?

########################################################################
echo "Generating ${amalH}..."
cat <<EOF > ${amalH}
/* This file is automatically generated. Edit at your own risk. */
#if !defined(ORG_FOSSIL_SCM_LIBFOSSIL_AMAL_H_INCLUDED)
#define ORG_FOSSIL_SCM_LIBFOSSIL_AMAL_H_INCLUDED
#undef FSL_AMALGAMATION_BUILD
#define FSL_AMALGAMATION_BUILD 1
EOF
cat VERSION.h >> ${amalH}
cat <<EOF >> ${amalH}
#if defined(HAVE_CONFIG_H)
#  include "config.h"
#endif
#include "${amalConf}"
#include "sqlite3.h"
EOF

{
  for i in ${ahIn[@]}; do
    echo "/* start of file $i */"
    cat $TOPDIR/$i
    echo "/* end of file $i */"
  done
  echo "#if defined(FSL_EXPOSE_INTERNAL_APIS)"
  echo "/* FSL_EXPOSE_INTERNAL_APIS is a compatibility crutch for fnc! */"
  echo "/* Do not use FSL_EXPOSE_INTERNAL_APIS unless you know you need it! */"
  cat ${dIncF}/internal.h
  echo "#endif /*defined(FSL_EXPOSE_INTERNAL_APIS)*/"

  echo '#endif /*ORG_FOSSIL_SCM_LIBFOSSIL_AMAL_H_INCLUDED*/'
} | sed -e '/[ ]*#[ ]*include[ ]*["].*h["]/d' >> ${amalH}



########################################################################
echo "Generating ${amalC}..."

{
  echo "/* This file is automatically generated. Edit at your own risk. */"
  echo "/* start of ${amalH} */"
  cat ${amalH}
  echo "/* end of ${amalH} */"
} > ${amalC}

{
  for i in ${acIn[@]}; do
    echo "/* start of file $i */"
    cat $TOPDIR/$i
    echo "/* end of file $i */"
  done
} | sed -e '/[ ]*#[ ]*include[ ]*["].*h["]/d' >> ${amalC}

function sayQuietly() {
  if [[ x0 = x${beQuiet} ]]; then
    $@
  fi
}

sayQuietly ls -la ${amalConf} ${amalH} ${amalC}

cflags=${CFLAGS--O0}
if [[ x1 = x${compileC} ]]; then
  echo "Attempting to compile (sanity check):"
  requireBin cc
  (set -x; cc -c -I. -I$TOPDIR/extsrc ${amalC} ${cflags}) || die $?
  rm -f libfossil.o
#else
#  echo "Skipping C compilation sanity check."
fi

sayQuietly echo "Reminder: it will need a local copy of sqlite3.h and sqlite3.c/.o/.so/etc to build."

########################################################################
# C++
dCpp=bindings/cpp
amalCpp=libfossil++.cpp
amalHpp=libfossil++.hpp
ahppIn=(
 ${dInc}/libfossil.hpp
)
acppIn=(
  ${dCpp}/Context.cpp
  ${dCpp}/Db.cpp
  ${dCpp}/Deck.cpp
  ${dCpp}/Exception.cpp
  ${dCpp}/Fossil.cpp
  ${dCpp}/OStream.cpp
)

echo "Generating ${amalHpp}..."
{
  echo '#if !defined(FSLPP_AMALGAMATION_BUILD)'
  echo '#  define FSLPP_AMALGAMATION_BUILD 1'
  echo '#endif'
  echo '#include "libfossil.h"'
} > ${amalHpp}
{
  for i in ${ahppIn[@]}; do
    echo "/* start of file $i */"
    cat $TOPDIR/$i
    echo "/* end of file $i */"
  done
} | sed  \
      -e '/[ ]*#[ ]*include[ ]*.*fossil.*\.h[>"]/d' \
      -e '/[ ]*#[ ]*include[ ]*.*".*config\.h[>"]/d' \
      >> ${amalHpp}

echo "Generating ${amalCpp}..."
echo '#include "libfossil++.hpp"' > ${amalCpp}
{
  for i in ${acppIn[@]}; do
    echo "/* start of file $i */"
    cat $TOPDIR/$i
    echo "/* end of file $i */"
  done
} | sed  \
      -e '/[ ]*#[ ]*include[ ]*.*fossil.*\.h.*[>"]/d' \
      >> ${amalCpp}

sayQuietly ls -la ${amalHpp} ${amalCpp}

if [[ x1 = x${compileCpp} ]]; then
  echo "Attempting to compile (sanity check):"
  requireBin c++
  (set -x; c++ -c -I. -I$TOPDIR/extsrc ${amalCpp} ${cflags}) || die $?
  rm -f libfossil++.o
#else
#  echo "Skipping C++ compilation sanity check."
fi

# /C++
########################################################################

function affirmInCheckout() {
  for d in .fslckout _FOSSIL_; do
    [[ -f $d ]] && return
  done
  die 1 "Not in a fossil checkout: $1"
}

########################################################################
# Build the distribution bundle for uploading to the web site...
if [[ x1 = x${doZip} ]]; then
  affirmInCheckout "cannot build zip file"
  echo "Creating ${amalZip}..."
  zip -q ${amalZip} ${amalC} ${amalH} ${amalConf} || die $?
  sayQuietly ls -la ${amalZip}
  echo "Reminder: the C++ amalgamation is intentionally not part of the zipped bundle."
else
  rm -f ${amalZip}
fi

if [[ x0 = x${doUv} ]]; then
  exit 0
fi
affirmInCheckout "cannot build unversioned content"

echo "This is a fossil checkout. Adding amalgamation as unversioned content..."
sqlVinfo="select e.mtime,b.uuid from event e, blob b where b.rid=e.objid and e.type='ci' order by e.mtime desc limit 1;"
# ^  ^^^^^^ ==> 12345.6789,'hash'
vinfo=$(fossil sql "${sqlVinfo}")
version=$(echo ${vinfo} | cut -d\' -f2)

{
  echo "<div class='fossil-doc' data-title='Downloads'>"
  echo "<style>#download-list{ line-height: 1.5; font-size: 125%; white-space: pre-wrap; }</style>"
  echo "<p>This page hosts builds of the libfossil "
  echo "<a href='../wiki/AmalgamationBuild'>AmalgamationBuild</a>. "
  echo "It only hosts the \"latest\" build and is updated periodically by a "
  echo "project contributor."
  echo "</p>"
  echo "<pre id='download-list'>"
  echo "<a href='${amalZip}'>${amalZip}</a>"
  echo "Size:" $(ls -la ${amalZip} | awk '{print $5}') "bytes"
  echo "Last updated (YYYY-MM-DD):" \
       $(fossil sql "select strftime('%Y-%m-%d %H:%M',${vinfo%%,*})" | cut -d\' -f2) UTC
  echo "Source code version: <a href='../info/${version:0:16}'>${version:0:16}</a>"
  echo "Zip file SHA3-256 hash:" $(fossil sha3sum ${amalZip} | cut -d' ' -f1)
  echo "</pre>"
} > ${amalHtml}

fossil uv add ${amalZip} ${amalHtml} --mtime ${vinfo%%,*}

echo
echo "Unversioned repository content:"
fossil uv list --glob "*amal*"
echo
echo "To push the amalgamation to the repo:"
echo "  fossil uv sync"
